version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tushar
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meettrack
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    command: ["api"]
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://tushar:password@db:5432/meettrack
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: ["worker"]
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://tushar:password@db:5432/meettrack
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    # Enable NVIDIA GPU for faster-whisper and pyannote inside Docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  postgres_data:
  redis_data:
