"""add recorded_date

Revision ID: 69bcfd6a1f94
Revises: 75a9c3e579b6
Create Date: 2026-07-02 12:37:51.576941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69bcfd6a1f94'
down_revision: Union[str, Sequence[str], None] = '75a9c3e579b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('recorded_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'recorded_date')
    # ### end Alembic commands ###
