"""add multi user support

Revision ID: 6d5982a6ef60
Revises: c5d3d2c02345
Create Date: 2026-09-17 10:57:13.888229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d5982a6ef60'
down_revision: Union[str, Sequence[str], None] = 'c5d3d2c02345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meetings', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_calendar_token', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_calendar_token')
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'owner_id')
    # ### end Alembic commands ###
