"""Add participant_id to tasks

Revision ID: acb2b1b03513
Revises: 69bcfd6a1f94
Create Date: 2026-07-03 12:25:55.722486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb2b1b03513'
down_revision: Union[str, Sequence[str], None] = '69bcfd6a1f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'meeting_participants', ['participant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'participant_id')
    # ### end Alembic commands ###
